import type { Activity, GraphEdge, GraphNode } from "./types";

export const DEMO_NODES: GraphNode[] = [
  {
    id: "incident-1042",
    label: "INC-1042",
    detail: "Credential access chain",
    kind: "Incident",
    risk: "critical",
    x: 445,
    y: 252,
    observedAgo: 1,
    confidence: 96,
    properties: {
      Status: "Investigating",
      Owner: "SOC / Tier 2",
      Workspace: "Production",
    },
    evidence: {
      source: "SentinelFlow correlation",
      observedAt: "2026-07-28 13:42 KST",
      description:
        "Five independently observed events share the same asset, identity, and outbound infrastructure.",
    },
  },
  {
    id: "asset-fin-07",
    label: "FIN-WS-07",
    detail: "Windows workstation",
    kind: "Asset",
    risk: "high",
    x: 250,
    y: 165,
    observedAgo: 3,
    confidence: 99,
    properties: {
      OS: "Windows 11",
      Owner: "Finance",
      Sensor: "EDR-SEOUL-02",
    },
    evidence: {
      source: "Endpoint telemetry",
      observedAt: "2026-07-28 13:31 KST",
      description: "PowerShell spawned an unsigned process from a user-writable directory.",
    },
  },
  {
    id: "identity-mina",
    label: "m.park",
    detail: "Privileged identity",
    kind: "Identity",
    risk: "high",
    x: 212,
    y: 342,
    observedAgo: 4,
    confidence: 91,
    properties: {
      Role: "Finance Admin",
      MFA: "Enabled",
      Directory: "corp.local",
    },
    evidence: {
      source: "Identity provider",
      observedAt: "2026-07-28 13:25 KST",
      description: "The identity authenticated from FIN-WS-07 outside its normal session pattern.",
    },
  },
  {
    id: "file-loader",
    label: "invoice_viewer.exe",
    detail: "SHA-256 · 9e81…0d2a",
    kind: "File",
    risk: "critical",
    x: 447,
    y: 92,
    observedAgo: 2,
    confidence: 98,
    properties: {
      SHA256: "9e81…0d2a",
      Size: "482 KB",
      Signature: "Unsigned",
    },
    evidence: {
      source: "Malware sandbox",
      observedAt: "2026-07-28 13:35 KST",
      description: "Static and behavioral analysis identified a credential-dumping loader.",
    },
  },
  {
    id: "ip-c2",
    label: "185.220.101.17",
    detail: "Command & control",
    kind: "IPAddress",
    risk: "critical",
    x: 661,
    y: 143,
    observedAgo: 2,
    confidence: 94,
    properties: {
      ASN: "AS60729",
      Country: "NL",
      "First seen": "2026-07-26",
    },
    evidence: {
      source: "Network detection",
      observedAt: "2026-07-28 13:37 KST",
      description: "Repeated TLS beaconing was observed at a stable 60-second interval.",
    },
  },
  {
    id: "domain-update",
    label: "cdn-sync.cloud",
    detail: "Newly registered domain",
    kind: "Domain",
    risk: "high",
    x: 733,
    y: 286,
    observedAgo: 5,
    confidence: 88,
    properties: {
      Registrar: "NameSecure",
      Age: "4 days",
      Nameserver: "ns1.host.tld",
    },
    evidence: {
      source: "Passive DNS",
      observedAt: "2026-07-28 12:58 KST",
      description: "The domain resolved to the incident command-and-control address.",
    },
  },
  {
    id: "technique-t1003",
    label: "T1003",
    detail: "OS Credential Dumping",
    kind: "AttackTechnique",
    risk: "critical",
    x: 578,
    y: 390,
    observedAgo: 6,
    confidence: 93,
    properties: {
      Tactic: "Credential Access",
      Version: "ATT&CK v18",
      Mapping: "Behavioral",
    },
    evidence: {
      source: "Sigma · proc_access_lsass",
      observedAt: "2026-07-28 12:43 KST",
      description: "Process access behavior matched credential dumping detection logic.",
    },
  },
  {
    id: "malware-stealc",
    label: "StealC",
    detail: "Infostealer family",
    kind: "Malware",
    risk: "critical",
    x: 386,
    y: 425,
    observedAgo: 8,
    confidence: 87,
    properties: {
      Family: "StealC",
      Platform: "Windows",
      Classification: "Infostealer",
    },
    evidence: {
      source: "Threat intelligence feed",
      observedAt: "2026-07-28 11:51 KST",
      description: "File behavior and infrastructure overlap with a tracked StealC campaign.",
    },
  },
  {
    id: "actor-silk",
    label: "SILK TEMPEST",
    detail: "Tracked threat actor",
    kind: "ThreatActor",
    risk: "high",
    x: 808,
    y: 416,
    observedAgo: 18,
    confidence: 72,
    properties: {
      Motivation: "Financial",
      Region: "Unknown",
      "Tracking status": "Active",
    },
    evidence: {
      source: "Analyst assessment",
      observedAt: "2026-07-27 21:44 KST",
      description: "Infrastructure reuse suggests a possible link; attribution remains moderate.",
    },
  },
  {
    id: "asset-dc-01",
    label: "DC-SEOUL-01",
    detail: "Domain controller",
    kind: "Asset",
    risk: "medium",
    x: 96,
    y: 245,
    observedAgo: 14,
    confidence: 89,
    properties: {
      OS: "Windows Server 2022",
      Tier: "Critical",
      Sensor: "EDR-SEOUL-01",
    },
    evidence: {
      source: "Asset inventory",
      observedAt: "2026-07-27 23:20 KST",
      description: "The affected identity has an active administrative session on this asset.",
    },
  },
  {
    id: "ip-scanner",
    label: "198.51.100.42",
    detail: "Reconnaissance source",
    kind: "IPAddress",
    risk: "medium",
    x: 82,
    y: 73,
    observedAgo: 48,
    confidence: 66,
    properties: {
      ASN: "AS64500",
      Country: "US",
      "First seen": "2026-07-25",
    },
    evidence: {
      source: "Firewall telemetry",
      observedAt: "2026-07-26 09:04 KST",
      description: "Low-volume scanning preceded the first endpoint observation.",
    },
  },
  {
    id: "domain-benign",
    label: "login.microsoft.com",
    detail: "Known infrastructure",
    kind: "Domain",
    risk: "low",
    x: 850,
    y: 80,
    observedAgo: 70,
    confidence: 100,
    properties: {
      Classification: "Known good",
      Provider: "Microsoft",
      Action: "Excluded",
    },
    evidence: {
      source: "Allowlist policy",
      observedAt: "2026-07-25 12:10 KST",
      description: "Known service shown as an analyst-reviewed false-positive branch.",
    },
  },
];

export const DEMO_EDGES: GraphEdge[] = [
  {
    id: "e1",
    source: "asset-fin-07",
    target: "incident-1042",
    label: "part_of_incident",
    confidence: 99,
    critical: true,
  },
  {
    id: "e2",
    source: "identity-mina",
    target: "incident-1042",
    label: "part_of_incident",
    confidence: 91,
    critical: true,
  },
  {
    id: "e3",
    source: "file-loader",
    target: "asset-fin-07",
    label: "executed",
    confidence: 98,
    critical: true,
  },
  {
    id: "e4",
    source: "asset-fin-07",
    target: "ip-c2",
    label: "communicates_with",
    confidence: 94,
    critical: true,
  },
  {
    id: "e5",
    source: "domain-update",
    target: "ip-c2",
    label: "resolves_to",
    confidence: 88,
    critical: true,
  },
  {
    id: "e6",
    source: "incident-1042",
    target: "technique-t1003",
    label: "uses_technique",
    confidence: 93,
    critical: true,
  },
  {
    id: "e7",
    source: "malware-stealc",
    target: "technique-t1003",
    label: "uses_technique",
    confidence: 87,
    critical: true,
  },
  {
    id: "e8",
    source: "malware-stealc",
    target: "incident-1042",
    label: "related_to",
    confidence: 87,
  },
  {
    id: "e9",
    source: "actor-silk",
    target: "malware-stealc",
    label: "attributed_to",
    confidence: 72,
  },
  {
    id: "e10",
    source: "identity-mina",
    target: "asset-dc-01",
    label: "authenticated_to",
    confidence: 89,
  },
  {
    id: "e11",
    source: "ip-scanner",
    target: "asset-fin-07",
    label: "observed_on",
    confidence: 66,
  },
  {
    id: "e12",
    source: "domain-benign",
    target: "ip-c2",
    label: "related_to",
    confidence: 35,
  },
];

export const ACTIVITIES: Activity[] = [
  {
    id: "activity-1",
    title: "Critical path correlated",
    detail: "FIN-WS-07 → 185.220.101.17 → T1003",
    time: "2 min ago",
    severity: "critical",
    source: "Correlation engine",
  },
  {
    id: "activity-2",
    title: "STIX bundle imported",
    detail: "42 objects · 8 relationships · 0 rejected",
    time: "18 min ago",
    severity: "low",
    source: "TAXII / MISP",
  },
  {
    id: "activity-3",
    title: "New infrastructure linked",
    detail: "cdn-sync.cloud resolves to a known C2 address",
    time: "44 min ago",
    severity: "high",
    source: "Passive DNS",
  },
  {
    id: "activity-4",
    title: "Analyst verdict recorded",
    detail: "Attribution confidence adjusted from 61% to 72%",
    time: "1 h ago",
    severity: "medium",
    source: "SOC / Tier 2",
  },
];
